/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ContractCallReceiver from '../test/generated-artifacts/ContractCallReceiver.json';
import * as MultiSigWallet from '../test/generated-artifacts/MultiSigWallet.json';
import * as MultiSigWalletWithTimeLock from '../test/generated-artifacts/MultiSigWalletWithTimeLock.json';
import * as TestRejectEther from '../test/generated-artifacts/TestRejectEther.json';
import * as TestZeroExGovernor from '../test/generated-artifacts/TestZeroExGovernor.json';
import * as ZeroExGovernor from '../test/generated-artifacts/ZeroExGovernor.json';
export const artifacts = {
    MultiSigWallet: MultiSigWallet as ContractArtifact,
    MultiSigWalletWithTimeLock: MultiSigWalletWithTimeLock as ContractArtifact,
    ZeroExGovernor: ZeroExGovernor as ContractArtifact,
    ContractCallReceiver: ContractCallReceiver as ContractArtifact,
    TestRejectEther: TestRejectEther as ContractArtifact,
    TestZeroExGovernor: TestZeroExGovernor as ContractArtifact,
};
