/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../test/generated-wrappers/contract_call_receiver';
export * from '../test/generated-wrappers/multi_sig_wallet';
export * from '../test/generated-wrappers/multi_sig_wallet_with_time_lock';
export * from '../test/generated-wrappers/test_reject_ether';
export * from '../test/generated-wrappers/test_zero_ex_governor';
export * from '../test/generated-wrappers/zero_ex_governor';
