from typing import Any


class ContractFunction:
    @staticmethod
    def call() -> Any: ...
    ...


class Contract:
    class functions:
        def __getattr__(self, function_name) -> ContractFunction: ...
    ...
