/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Forwarder from '../test/generated-artifacts/Forwarder.json';
import * as IExchangeV2 from '../test/generated-artifacts/IExchangeV2.json';
import * as IForwarder from '../test/generated-artifacts/IForwarder.json';
import * as LibForwarderRichErrors from '../test/generated-artifacts/LibForwarderRichErrors.json';
import * as MixinExchangeWrapper from '../test/generated-artifacts/MixinExchangeWrapper.json';
import * as MixinReceiver from '../test/generated-artifacts/MixinReceiver.json';
import * as TestForwarder from '../test/generated-artifacts/TestForwarder.json';
export const artifacts = {
    Forwarder: Forwarder as ContractArtifact,
    MixinExchangeWrapper: MixinExchangeWrapper as ContractArtifact,
    MixinReceiver: MixinReceiver as ContractArtifact,
    IExchangeV2: IExchangeV2 as ContractArtifact,
    IForwarder: IForwarder as ContractArtifact,
    LibForwarderRichErrors: LibForwarderRichErrors as ContractArtifact,
    TestForwarder: TestForwarder as ContractArtifact,
};
