/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Forwarder from '../test/generated-artifacts/Forwarder.json';
import * as IAssets from '../test/generated-artifacts/IAssets.json';
import * as IForwarder from '../test/generated-artifacts/IForwarder.json';
import * as IForwarderCore from '../test/generated-artifacts/IForwarderCore.json';
import * as LibConstants from '../test/generated-artifacts/LibConstants.json';
import * as LibForwarderRichErrors from '../test/generated-artifacts/LibForwarderRichErrors.json';
import * as MixinAssets from '../test/generated-artifacts/MixinAssets.json';
import * as MixinExchangeWrapper from '../test/generated-artifacts/MixinExchangeWrapper.json';
import * as MixinForwarderCore from '../test/generated-artifacts/MixinForwarderCore.json';
import * as MixinWeth from '../test/generated-artifacts/MixinWeth.json';
import * as TestForwarder from '../test/generated-artifacts/TestForwarder.json';
export const artifacts = {
    Forwarder: Forwarder as ContractArtifact,
    MixinAssets: MixinAssets as ContractArtifact,
    MixinExchangeWrapper: MixinExchangeWrapper as ContractArtifact,
    MixinForwarderCore: MixinForwarderCore as ContractArtifact,
    MixinWeth: MixinWeth as ContractArtifact,
    IAssets: IAssets as ContractArtifact,
    IForwarder: IForwarder as ContractArtifact,
    IForwarderCore: IForwarderCore as ContractArtifact,
    LibConstants: LibConstants as ContractArtifact,
    LibForwarderRichErrors: LibForwarderRichErrors as ContractArtifact,
    TestForwarder: TestForwarder as ContractArtifact,
};
