/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Exchange from '../test/generated-artifacts/Exchange.json';
import * as IAssetProxy from '../test/generated-artifacts/IAssetProxy.json';
import * as IAssetProxyDispatcher from '../test/generated-artifacts/IAssetProxyDispatcher.json';
import * as IEIP1271Data from '../test/generated-artifacts/IEIP1271Data.json';
import * as IEIP1271Wallet from '../test/generated-artifacts/IEIP1271Wallet.json';
import * as IExchange from '../test/generated-artifacts/IExchange.json';
import * as IExchangeCore from '../test/generated-artifacts/IExchangeCore.json';
import * as IMatchOrders from '../test/generated-artifacts/IMatchOrders.json';
import * as IProtocolFees from '../test/generated-artifacts/IProtocolFees.json';
import * as ISignatureValidator from '../test/generated-artifacts/ISignatureValidator.json';
import * as IsolatedExchange from '../test/generated-artifacts/IsolatedExchange.json';
import * as ITransactions from '../test/generated-artifacts/ITransactions.json';
import * as ITransferSimulator from '../test/generated-artifacts/ITransferSimulator.json';
import * as IWallet from '../test/generated-artifacts/IWallet.json';
import * as IWrapperFunctions from '../test/generated-artifacts/IWrapperFunctions.json';
import * as LibExchangeRichErrorDecoder from '../test/generated-artifacts/LibExchangeRichErrorDecoder.json';
import * as MixinAssetProxyDispatcher from '../test/generated-artifacts/MixinAssetProxyDispatcher.json';
import * as MixinExchangeCore from '../test/generated-artifacts/MixinExchangeCore.json';
import * as MixinMatchOrders from '../test/generated-artifacts/MixinMatchOrders.json';
import * as MixinProtocolFees from '../test/generated-artifacts/MixinProtocolFees.json';
import * as MixinSignatureValidator from '../test/generated-artifacts/MixinSignatureValidator.json';
import * as MixinTransactions from '../test/generated-artifacts/MixinTransactions.json';
import * as MixinTransferSimulator from '../test/generated-artifacts/MixinTransferSimulator.json';
import * as MixinWrapperFunctions from '../test/generated-artifacts/MixinWrapperFunctions.json';
import * as ReentrancyTester from '../test/generated-artifacts/ReentrancyTester.json';
import * as TestAssetProxyDispatcher from '../test/generated-artifacts/TestAssetProxyDispatcher.json';
import * as TestExchangeInternals from '../test/generated-artifacts/TestExchangeInternals.json';
import * as TestFillRounding from '../test/generated-artifacts/TestFillRounding.json';
import * as TestLibExchangeRichErrorDecoder from '../test/generated-artifacts/TestLibExchangeRichErrorDecoder.json';
import * as TestProtocolFeeCollector from '../test/generated-artifacts/TestProtocolFeeCollector.json';
import * as TestProtocolFees from '../test/generated-artifacts/TestProtocolFees.json';
import * as TestProtocolFeesReceiver from '../test/generated-artifacts/TestProtocolFeesReceiver.json';
import * as TestTransactions from '../test/generated-artifacts/TestTransactions.json';
import * as TestValidatorWallet from '../test/generated-artifacts/TestValidatorWallet.json';
import * as TestWrapperFunctions from '../test/generated-artifacts/TestWrapperFunctions.json';
export const artifacts = {
    Exchange: Exchange as ContractArtifact,
    MixinAssetProxyDispatcher: MixinAssetProxyDispatcher as ContractArtifact,
    MixinExchangeCore: MixinExchangeCore as ContractArtifact,
    MixinMatchOrders: MixinMatchOrders as ContractArtifact,
    MixinProtocolFees: MixinProtocolFees as ContractArtifact,
    MixinSignatureValidator: MixinSignatureValidator as ContractArtifact,
    MixinTransactions: MixinTransactions as ContractArtifact,
    MixinTransferSimulator: MixinTransferSimulator as ContractArtifact,
    MixinWrapperFunctions: MixinWrapperFunctions as ContractArtifact,
    IAssetProxy: IAssetProxy as ContractArtifact,
    IAssetProxyDispatcher: IAssetProxyDispatcher as ContractArtifact,
    IEIP1271Data: IEIP1271Data as ContractArtifact,
    IEIP1271Wallet: IEIP1271Wallet as ContractArtifact,
    IExchange: IExchange as ContractArtifact,
    IExchangeCore: IExchangeCore as ContractArtifact,
    IMatchOrders: IMatchOrders as ContractArtifact,
    IProtocolFees: IProtocolFees as ContractArtifact,
    ISignatureValidator: ISignatureValidator as ContractArtifact,
    ITransactions: ITransactions as ContractArtifact,
    ITransferSimulator: ITransferSimulator as ContractArtifact,
    IWallet: IWallet as ContractArtifact,
    IWrapperFunctions: IWrapperFunctions as ContractArtifact,
    LibExchangeRichErrorDecoder: LibExchangeRichErrorDecoder as ContractArtifact,
    IsolatedExchange: IsolatedExchange as ContractArtifact,
    ReentrancyTester: ReentrancyTester as ContractArtifact,
    TestAssetProxyDispatcher: TestAssetProxyDispatcher as ContractArtifact,
    TestExchangeInternals: TestExchangeInternals as ContractArtifact,
    TestFillRounding: TestFillRounding as ContractArtifact,
    TestLibExchangeRichErrorDecoder: TestLibExchangeRichErrorDecoder as ContractArtifact,
    TestProtocolFeeCollector: TestProtocolFeeCollector as ContractArtifact,
    TestProtocolFees: TestProtocolFees as ContractArtifact,
    TestProtocolFeesReceiver: TestProtocolFeesReceiver as ContractArtifact,
    TestTransactions: TestTransactions as ContractArtifact,
    TestValidatorWallet: TestValidatorWallet as ContractArtifact,
    TestWrapperFunctions: TestWrapperFunctions as ContractArtifact,
};
