/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../test/generated-wrappers/exchange';
export * from '../test/generated-wrappers/i_asset_proxy';
export * from '../test/generated-wrappers/i_asset_proxy_dispatcher';
export * from '../test/generated-wrappers/i_e_i_p1271_data';
export * from '../test/generated-wrappers/i_e_i_p1271_wallet';
export * from '../test/generated-wrappers/i_exchange';
export * from '../test/generated-wrappers/i_exchange_core';
export * from '../test/generated-wrappers/i_match_orders';
export * from '../test/generated-wrappers/i_protocol_fees';
export * from '../test/generated-wrappers/i_signature_validator';
export * from '../test/generated-wrappers/i_transactions';
export * from '../test/generated-wrappers/i_transfer_simulator';
export * from '../test/generated-wrappers/i_wallet';
export * from '../test/generated-wrappers/i_wrapper_functions';
export * from '../test/generated-wrappers/isolated_exchange';
export * from '../test/generated-wrappers/lib_exchange_rich_error_decoder';
export * from '../test/generated-wrappers/mixin_asset_proxy_dispatcher';
export * from '../test/generated-wrappers/mixin_exchange_core';
export * from '../test/generated-wrappers/mixin_match_orders';
export * from '../test/generated-wrappers/mixin_protocol_fees';
export * from '../test/generated-wrappers/mixin_signature_validator';
export * from '../test/generated-wrappers/mixin_transactions';
export * from '../test/generated-wrappers/mixin_transfer_simulator';
export * from '../test/generated-wrappers/mixin_wrapper_functions';
export * from '../test/generated-wrappers/reentrancy_tester';
export * from '../test/generated-wrappers/test_asset_proxy_dispatcher';
export * from '../test/generated-wrappers/test_exchange_internals';
export * from '../test/generated-wrappers/test_lib_exchange_rich_error_decoder';
export * from '../test/generated-wrappers/test_protocol_fee_collector';
export * from '../test/generated-wrappers/test_protocol_fees';
export * from '../test/generated-wrappers/test_protocol_fees_receiver';
export * from '../test/generated-wrappers/test_signature_validator';
export * from '../test/generated-wrappers/test_transactions';
export * from '../test/generated-wrappers/test_validator_wallet';
export * from '../test/generated-wrappers/test_wrapper_functions';
