/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Coordinator from '../generated-artifacts/Coordinator.json';
import * as CoordinatorRegistry from '../generated-artifacts/CoordinatorRegistry.json';
import * as TestLibs from '../generated-artifacts/TestLibs.json';
import * as TestMixins from '../generated-artifacts/TestMixins.json';
export const artifacts = {
    Coordinator: Coordinator as ContractArtifact,
    CoordinatorRegistry: CoordinatorRegistry as ContractArtifact,
    TestLibs: TestLibs as ContractArtifact,
    TestMixins: TestMixins as ContractArtifact,
};
