/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Coordinator from '../generated-artifacts/Coordinator.json';
import * as CoordinatorRegistry from '../generated-artifacts/CoordinatorRegistry.json';
import * as LibConstants from '../generated-artifacts/LibConstants.json';
import * as LibCoordinatorApproval from '../generated-artifacts/LibCoordinatorApproval.json';
import * as LibCoordinatorRichErrors from '../generated-artifacts/LibCoordinatorRichErrors.json';
import * as LibEIP712CoordinatorDomain from '../generated-artifacts/LibEIP712CoordinatorDomain.json';
export const artifacts = {
    Coordinator: Coordinator as ContractArtifact,
    CoordinatorRegistry: CoordinatorRegistry as ContractArtifact,
    LibCoordinatorApproval: LibCoordinatorApproval as ContractArtifact,
    LibCoordinatorRichErrors: LibCoordinatorRichErrors as ContractArtifact,
    LibEIP712CoordinatorDomain: LibEIP712CoordinatorDomain as ContractArtifact,
    LibConstants: LibConstants as ContractArtifact,
};
