/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as DummyERC1155Receiver from '../generated-artifacts/DummyERC1155Receiver.json';
import * as ERC1155 from '../generated-artifacts/ERC1155.json';
import * as ERC1155Mintable from '../generated-artifacts/ERC1155Mintable.json';
import * as IERC1155Receiver from '../generated-artifacts/IERC1155Receiver.json';
export const artifacts = {
    ERC1155: ERC1155 as ContractArtifact,
    ERC1155Mintable: ERC1155Mintable as ContractArtifact,
    IERC1155Receiver: IERC1155Receiver as ContractArtifact,
    DummyERC1155Receiver: DummyERC1155Receiver as ContractArtifact,
};
