/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../generated-wrappers/address';
export * from '../generated-wrappers/dummy_erc1155_receiver';
export * from '../generated-wrappers/dummy_erc1155_token';
export * from '../generated-wrappers/i_erc1155_token_receiver';
export * from '../generated-wrappers/ierc1155';
export * from '../generated-wrappers/invalid_erc1155_receiver';
export * from '../generated-wrappers/my_erc1155';
