/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Exchange from '../generated-artifacts/Exchange.json';
import * as IExchange from '../generated-artifacts/IExchange.json';
export const artifacts = { Exchange: Exchange as ContractArtifact, IExchange: IExchange as ContractArtifact };
