/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Exchange from '../generated-artifacts/Exchange.json';
import * as ExchangeWrapper from '../generated-artifacts/ExchangeWrapper.json';
import * as IAssetProxyDispatcher from '../generated-artifacts/IAssetProxyDispatcher.json';
import * as IEIP1271Wallet from '../generated-artifacts/IEIP1271Wallet.json';
import * as IExchange from '../generated-artifacts/IExchange.json';
import * as IExchangeCore from '../generated-artifacts/IExchangeCore.json';
import * as IMatchOrders from '../generated-artifacts/IMatchOrders.json';
import * as ISignatureValidator from '../generated-artifacts/ISignatureValidator.json';
import * as ITransactions from '../generated-artifacts/ITransactions.json';
import * as IWallet from '../generated-artifacts/IWallet.json';
import * as IWrapperFunctions from '../generated-artifacts/IWrapperFunctions.json';
import * as ReentrantERC20Token from '../generated-artifacts/ReentrantERC20Token.json';
import * as TestAssetProxyDispatcher from '../generated-artifacts/TestAssetProxyDispatcher.json';
import * as TestExchangeInternals from '../generated-artifacts/TestExchangeInternals.json';
import * as TestExchangeMath from '../generated-artifacts/TestExchangeMath.json';
import * as TestIsolatedExchange from '../generated-artifacts/TestIsolatedExchange.json';
import * as TestLibExchangeRichErrorDecoder from '../generated-artifacts/TestLibExchangeRichErrorDecoder.json';
import * as TestSignatureValidator from '../generated-artifacts/TestSignatureValidator.json';
import * as TestValidatorWallet from '../generated-artifacts/TestValidatorWallet.json';
import * as Whitelist from '../generated-artifacts/Whitelist.json';
export const artifacts = {
    ExchangeWrapper: ExchangeWrapper as ContractArtifact,
    Whitelist: Whitelist as ContractArtifact,
    Exchange: Exchange as ContractArtifact,
    IAssetProxyDispatcher: IAssetProxyDispatcher as ContractArtifact,
    IEIP1271Wallet: IEIP1271Wallet as ContractArtifact,
    IExchange: IExchange as ContractArtifact,
    IExchangeCore: IExchangeCore as ContractArtifact,
    IMatchOrders: IMatchOrders as ContractArtifact,
    ISignatureValidator: ISignatureValidator as ContractArtifact,
    ITransactions: ITransactions as ContractArtifact,
    IWallet: IWallet as ContractArtifact,
    IWrapperFunctions: IWrapperFunctions as ContractArtifact,
    ReentrantERC20Token: ReentrantERC20Token as ContractArtifact,
    TestAssetProxyDispatcher: TestAssetProxyDispatcher as ContractArtifact,
    TestExchangeInternals: TestExchangeInternals as ContractArtifact,
    TestExchangeMath: TestExchangeMath as ContractArtifact,
    TestIsolatedExchange: TestIsolatedExchange as ContractArtifact,
    TestLibExchangeRichErrorDecoder: TestLibExchangeRichErrorDecoder as ContractArtifact,
    TestSignatureValidator: TestSignatureValidator as ContractArtifact,
    TestValidatorWallet: TestValidatorWallet as ContractArtifact,
};
