/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as LibZrxToken from '../generated-artifacts/LibZrxToken.json';
import * as MixinStake from '../generated-artifacts/MixinStake.json';
import * as MixinVaultCore from '../generated-artifacts/MixinVaultCore.json';
import * as Staking from '../generated-artifacts/Staking.json';
import * as ZrxVault from '../generated-artifacts/ZrxVault.json';
export const artifacts = {
    Staking: Staking as ContractArtifact,
    MixinStake: MixinStake as ContractArtifact,
    MixinVaultCore: MixinVaultCore as ContractArtifact,
    ZrxVault: ZrxVault as ContractArtifact,
    LibZrxToken: LibZrxToken as ContractArtifact,
};
