/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Empty from '../generated-artifacts/Empty.json';
export const artifacts = { Empty: Empty as ContractArtifact };
