/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as StakingWithTokens from '../generated-artifacts/StakingWithTokens.json';
export const artifacts = { StakingWithTokens: StakingWithTokens as ContractArtifact };
