/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as LibAbiEncoder from '../generated-artifacts/LibAbiEncoder.json';
import * as LibAssetProxyErrors from '../generated-artifacts/LibAssetProxyErrors.json';
import * as LibConstants from '../generated-artifacts/LibConstants.json';
import * as LibEIP712ExchangeDomain from '../generated-artifacts/LibEIP712ExchangeDomain.json';
import * as LibFillResults from '../generated-artifacts/LibFillResults.json';
import * as LibMath from '../generated-artifacts/LibMath.json';
import * as LibOrder from '../generated-artifacts/LibOrder.json';
import * as LibZeroExTransaction from '../generated-artifacts/LibZeroExTransaction.json';
import * as TestLibs from '../generated-artifacts/TestLibs.json';
export const artifacts = {
    LibAbiEncoder: LibAbiEncoder as ContractArtifact,
    LibAssetProxyErrors: LibAssetProxyErrors as ContractArtifact,
    LibConstants: LibConstants as ContractArtifact,
    LibFillResults: LibFillResults as ContractArtifact,
    LibMath: LibMath as ContractArtifact,
    LibOrder: LibOrder as ContractArtifact,
    LibZeroExTransaction: LibZeroExTransaction as ContractArtifact,
    LibEIP712ExchangeDomain: LibEIP712ExchangeDomain as ContractArtifact,
    TestLibs: TestLibs as ContractArtifact,
};
