/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as IWallet from '../generated-artifacts/IWallet.json';
import * as LibEIP712ExchangeDomain from '../generated-artifacts/LibEIP712ExchangeDomain.json';
import * as LibExchangeRichErrors from '../generated-artifacts/LibExchangeRichErrors.json';
import * as LibMath from '../generated-artifacts/LibMath.json';
import * as LibMathRichErrors from '../generated-artifacts/LibMathRichErrors.json';
import * as LibOrder from '../generated-artifacts/LibOrder.json';
import * as LibZeroExTransaction from '../generated-artifacts/LibZeroExTransaction.json';
export const artifacts = {
    IWallet: IWallet as ContractArtifact,
    LibEIP712ExchangeDomain: LibEIP712ExchangeDomain as ContractArtifact,
    LibExchangeRichErrors: LibExchangeRichErrors as ContractArtifact,
    LibMath: LibMath as ContractArtifact,
    LibMathRichErrors: LibMathRichErrors as ContractArtifact,
    LibOrder: LibOrder as ContractArtifact,
    LibZeroExTransaction: LibZeroExTransaction as ContractArtifact,
};
