/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as AssetBalance from '../test/generated-artifacts/AssetBalance.json';
import * as DevUtils from '../test/generated-artifacts/DevUtils.json';
import * as EthBalanceChecker from '../test/generated-artifacts/EthBalanceChecker.json';
import * as ExternalFunctions from '../test/generated-artifacts/ExternalFunctions.json';
import * as LibAssetData from '../test/generated-artifacts/LibAssetData.json';
import * as LibDydxBalance from '../test/generated-artifacts/LibDydxBalance.json';
import * as LibTransactionDecoder from '../test/generated-artifacts/LibTransactionDecoder.json';
import * as OrderTransferSimulationUtils from '../test/generated-artifacts/OrderTransferSimulationUtils.json';
import * as OrderValidationUtils from '../test/generated-artifacts/OrderValidationUtils.json';
import * as TestLibDydxBalance from '../test/generated-artifacts/TestLibDydxBalance.json';
export const artifacts = {
    AssetBalance: AssetBalance as ContractArtifact,
    DevUtils: DevUtils as ContractArtifact,
    EthBalanceChecker: EthBalanceChecker as ContractArtifact,
    ExternalFunctions: ExternalFunctions as ContractArtifact,
    LibAssetData: LibAssetData as ContractArtifact,
    LibDydxBalance: LibDydxBalance as ContractArtifact,
    LibTransactionDecoder: LibTransactionDecoder as ContractArtifact,
    OrderTransferSimulationUtils: OrderTransferSimulationUtils as ContractArtifact,
    OrderValidationUtils: OrderValidationUtils as ContractArtifact,
    TestLibDydxBalance: TestLibDydxBalance as ContractArtifact,
};
