/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as DevUtils from '../test/generated-artifacts/DevUtils.json';
import * as EthBalanceChecker from '../test/generated-artifacts/EthBalanceChecker.json';
import * as LibAssetData from '../test/generated-artifacts/LibAssetData.json';
import * as LibTransactionDecoder from '../test/generated-artifacts/LibTransactionDecoder.json';
import * as OrderTransferSimulationUtils from '../test/generated-artifacts/OrderTransferSimulationUtils.json';
import * as OrderValidationUtils from '../test/generated-artifacts/OrderValidationUtils.json';
export const artifacts = {
    DevUtils: DevUtils as ContractArtifact,
    EthBalanceChecker: EthBalanceChecker as ContractArtifact,
    LibAssetData: LibAssetData as ContractArtifact,
    LibTransactionDecoder: LibTransactionDecoder as ContractArtifact,
    OrderTransferSimulationUtils: OrderTransferSimulationUtils as ContractArtifact,
    OrderValidationUtils: OrderValidationUtils as ContractArtifact,
};
