/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ERC1155Proxy from '../generated-artifacts/ERC1155Proxy.json';
import * as ERC20BridgeProxy from '../generated-artifacts/ERC20BridgeProxy.json';
import * as ERC20Proxy from '../generated-artifacts/ERC20Proxy.json';
import * as ERC721Proxy from '../generated-artifacts/ERC721Proxy.json';
import * as Eth2DaiBridge from '../generated-artifacts/Eth2DaiBridge.json';
import * as IAssetData from '../generated-artifacts/IAssetData.json';
import * as IAssetProxy from '../generated-artifacts/IAssetProxy.json';
import * as IAssetProxyDispatcher from '../generated-artifacts/IAssetProxyDispatcher.json';
import * as IAuthorizable from '../generated-artifacts/IAuthorizable.json';
import * as IERC20Bridge from '../generated-artifacts/IERC20Bridge.json';
import * as IEth2Dai from '../generated-artifacts/IEth2Dai.json';
import * as IWallet from '../generated-artifacts/IWallet.json';
import * as MixinAssetProxyDispatcher from '../generated-artifacts/MixinAssetProxyDispatcher.json';
import * as MixinAuthorizable from '../generated-artifacts/MixinAuthorizable.json';
import * as MultiAssetProxy from '../generated-artifacts/MultiAssetProxy.json';
import * as Ownable from '../generated-artifacts/Ownable.json';
import * as StaticCallProxy from '../generated-artifacts/StaticCallProxy.json';
import * as TestERC20Bridge from '../generated-artifacts/TestERC20Bridge.json';
import * as TestEth2DaiBridge from '../generated-artifacts/TestEth2DaiBridge.json';
import * as TestStaticCallTarget from '../generated-artifacts/TestStaticCallTarget.json';
export const artifacts = {
    MixinAssetProxyDispatcher: MixinAssetProxyDispatcher as ContractArtifact,
    MixinAuthorizable: MixinAuthorizable as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ERC1155Proxy: ERC1155Proxy as ContractArtifact,
    ERC20BridgeProxy: ERC20BridgeProxy as ContractArtifact,
    ERC20Proxy: ERC20Proxy as ContractArtifact,
    ERC721Proxy: ERC721Proxy as ContractArtifact,
    MultiAssetProxy: MultiAssetProxy as ContractArtifact,
    StaticCallProxy: StaticCallProxy as ContractArtifact,
    Eth2DaiBridge: Eth2DaiBridge as ContractArtifact,
    IAssetData: IAssetData as ContractArtifact,
    IAssetProxy: IAssetProxy as ContractArtifact,
    IAssetProxyDispatcher: IAssetProxyDispatcher as ContractArtifact,
    IAuthorizable: IAuthorizable as ContractArtifact,
    IERC20Bridge: IERC20Bridge as ContractArtifact,
    IEth2Dai: IEth2Dai as ContractArtifact,
    IWallet: IWallet as ContractArtifact,
    TestERC20Bridge: TestERC20Bridge as ContractArtifact,
    TestEth2DaiBridge: TestEth2DaiBridge as ContractArtifact,
    TestStaticCallTarget: TestStaticCallTarget as ContractArtifact,
};
