/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../generated-wrappers/abi_gen_dummy';
export * from '../generated-wrappers/lib_dummy';
export * from '../generated-wrappers/test_lib_dummy';
