/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
export * from '../../output/typescript/abi_gen_dummy';
export * from '../../output/typescript/lib_dummy';
export * from '../../output/typescript/test_lib_dummy';
