/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as LibAssetDataTransfer from '../generated-artifacts/LibAssetDataTransfer.json';
import * as LibAssetDataTransferRichErrors from '../generated-artifacts/LibAssetDataTransferRichErrors.json';
import * as LibWethUtilsRichErrors from '../generated-artifacts/LibWethUtilsRichErrors.json';
import * as MixinWethUtils from '../generated-artifacts/MixinWethUtils.json';
export const artifacts = {
    LibAssetDataTransfer: LibAssetDataTransfer as ContractArtifact,
    MixinWethUtils: MixinWethUtils as ContractArtifact,
    LibAssetDataTransferRichErrors: LibAssetDataTransferRichErrors as ContractArtifact,
    LibWethUtilsRichErrors: LibWethUtilsRichErrors as ContractArtifact,
};
