/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as AbiGenDummy from '../../artifacts/AbiGenDummy.json';
import * as LibDummy from '../../artifacts/LibDummy.json';
import * as TestLibDummy from '../../artifacts/TestLibDummy.json';
export const artifacts = {
    AbiGenDummy: AbiGenDummy as ContractArtifact,
    LibDummy: LibDummy as ContractArtifact,
    TestLibDummy: TestLibDummy as ContractArtifact,
};
