/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as TestEth2Dai from '../test/generated-artifacts/TestEth2Dai.json';
import * as TestEth2DaiBridge from '../test/generated-artifacts/TestEth2DaiBridge.json';
import * as TestFramework from '../test/generated-artifacts/TestFramework.json';
import * as TestUniswapBridge from '../test/generated-artifacts/TestUniswapBridge.json';
import * as TestUniswapExchange from '../test/generated-artifacts/TestUniswapExchange.json';
import * as TestUniswapExchangeFactory from '../test/generated-artifacts/TestUniswapExchangeFactory.json';
export const artifacts = {
    TestEth2Dai: TestEth2Dai as ContractArtifact,
    TestEth2DaiBridge: TestEth2DaiBridge as ContractArtifact,
    TestFramework: TestFramework as ContractArtifact,
    TestUniswapBridge: TestUniswapBridge as ContractArtifact,
    TestUniswapExchange: TestUniswapExchange as ContractArtifact,
    TestUniswapExchangeFactory: TestUniswapExchangeFactory as ContractArtifact,
};
