/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ChainlinkStopLimit from '../test/generated-artifacts/ChainlinkStopLimit.json';
import * as ENSValidator from '../test/generated-artifacts/ENSValidator.json';
import * as IChainlinkAggregator from '../test/generated-artifacts/IChainlinkAggregator.json';
import * as IENS from '../test/generated-artifacts/IENS.json';
import * as IResolver from '../test/generated-artifacts/IResolver.json';
import * as TestChainlinkAggregator from '../test/generated-artifacts/TestChainlinkAggregator.json';
import * as TestContractWrapper from '../test/generated-artifacts/TestContractWrapper.json';
import * as TestDydxUser from '../test/generated-artifacts/TestDydxUser.json';
import * as TestEth2Dai from '../test/generated-artifacts/TestEth2Dai.json';
import * as TestEth2DaiBridge from '../test/generated-artifacts/TestEth2DaiBridge.json';
import * as TestFramework from '../test/generated-artifacts/TestFramework.json';
import * as TestMainnetAggregatorFills from '../test/generated-artifacts/TestMainnetAggregatorFills.json';
import * as TestSignatureValidationWallet from '../test/generated-artifacts/TestSignatureValidationWallet.json';
import * as TestUniswapBridge from '../test/generated-artifacts/TestUniswapBridge.json';
import * as TestUniswapExchange from '../test/generated-artifacts/TestUniswapExchange.json';
import * as TestUniswapExchangeFactory from '../test/generated-artifacts/TestUniswapExchangeFactory.json';
export const artifacts = {
    ChainlinkStopLimit: ChainlinkStopLimit as ContractArtifact,
    ENSValidator: ENSValidator as ContractArtifact,
    IChainlinkAggregator: IChainlinkAggregator as ContractArtifact,
    IENS: IENS as ContractArtifact,
    IResolver: IResolver as ContractArtifact,
    TestChainlinkAggregator: TestChainlinkAggregator as ContractArtifact,
    TestContractWrapper: TestContractWrapper as ContractArtifact,
    TestDydxUser: TestDydxUser as ContractArtifact,
    TestEth2Dai: TestEth2Dai as ContractArtifact,
    TestEth2DaiBridge: TestEth2DaiBridge as ContractArtifact,
    TestFramework: TestFramework as ContractArtifact,
    TestMainnetAggregatorFills: TestMainnetAggregatorFills as ContractArtifact,
    TestSignatureValidationWallet: TestSignatureValidationWallet as ContractArtifact,
    TestUniswapBridge: TestUniswapBridge as ContractArtifact,
    TestUniswapExchange: TestUniswapExchange as ContractArtifact,
    TestUniswapExchangeFactory: TestUniswapExchangeFactory as ContractArtifact,
};
