export const feesRequestSchema = {
    id: '/OrderConfigRequest',
    type: 'object',
    properties: {
        exchangeAddress: { $ref: '/Address' },
        maker: { $ref: '/Address' },
        taker: { $ref: '/Address' },
        makerTokenAddress: { $ref: '/Address' },
        takerTokenAddress: { $ref: '/Address' },
        makerAssetAmount: { $ref: '/Number' },
        takerAssetAmount: { $ref: '/Number' },
        expirationTimeSeconds: { $ref: '/Number' },
        salt: { $ref: '/Number' },
    },
    required: [
        'exchangeAddress',
        'maker',
        'taker',
        'makerTokenAddress',
        'takerTokenAddress',
        'makerAssetAmount',
        'takerAssetAmount',
        'expirationTimeSeconds',
        'salt',
    ],
};
