/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as DeploymentConstants from '../test/generated-artifacts/DeploymentConstants.json';
import * as ERC20BridgeSampler from '../test/generated-artifacts/ERC20BridgeSampler.json';
import * as IERC20BridgeSampler from '../test/generated-artifacts/IERC20BridgeSampler.json';
import * as IEth2Dai from '../test/generated-artifacts/IEth2Dai.json';
import * as IKyberNetwork from '../test/generated-artifacts/IKyberNetwork.json';
import * as IUniswapExchangeQuotes from '../test/generated-artifacts/IUniswapExchangeQuotes.json';
import * as LibERC20Token from '../test/generated-artifacts/LibERC20Token.json';
import * as TestERC20BridgeSampler from '../test/generated-artifacts/TestERC20BridgeSampler.json';
export const artifacts = {
    DeploymentConstants: DeploymentConstants as ContractArtifact,
    ERC20BridgeSampler: ERC20BridgeSampler as ContractArtifact,
    IERC20BridgeSampler: IERC20BridgeSampler as ContractArtifact,
    IEth2Dai: IEth2Dai as ContractArtifact,
    IKyberNetwork: IKyberNetwork as ContractArtifact,
    IUniswapExchangeQuotes: IUniswapExchangeQuotes as ContractArtifact,
    LibERC20Token: LibERC20Token as ContractArtifact,
    TestERC20BridgeSampler: TestERC20BridgeSampler as ContractArtifact,
};
