/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as AdvancedTokenInteract from '../generated-artifacts/AdvancedTokenInteract.json';
import * as ExchangeReader from '../generated-artifacts/ExchangeReader.json';
import * as ExchangeWrapper from '../generated-artifacts/ExchangeWrapper.json';
import * as GeneralERC20 from '../generated-artifacts/GeneralERC20.json';
import * as MathHelpers from '../generated-artifacts/MathHelpers.json';
import * as SafeMath from '../generated-artifacts/SafeMath.json';
import * as TokenInteract from '../generated-artifacts/TokenInteract.json';
import * as ZeroExV2MultiOrderExchangeWrapper from '../generated-artifacts/ZeroExV2MultiOrderExchangeWrapper.json';
import * as ZeroExV3ExchangeWrapper from '../generated-artifacts/ZeroExV3ExchangeWrapper.json';
export const artifacts = {
    ZeroExV2MultiOrderExchangeWrapper: ZeroExV2MultiOrderExchangeWrapper as ContractArtifact,
    ZeroExV3ExchangeWrapper: ZeroExV3ExchangeWrapper as ContractArtifact,
    ExchangeReader: ExchangeReader as ContractArtifact,
    ExchangeWrapper: ExchangeWrapper as ContractArtifact,
    AdvancedTokenInteract: AdvancedTokenInteract as ContractArtifact,
    GeneralERC20: GeneralERC20 as ContractArtifact,
    MathHelpers: MathHelpers as ContractArtifact,
    SafeMath: SafeMath as ContractArtifact,
    TokenInteract: TokenInteract as ContractArtifact,
};
