/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Broker from '../test/generated-artifacts/Broker.json';
export const artifacts = { Broker: Broker as ContractArtifact };
