/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Authorizable from '../generated-artifacts/Authorizable.json';
import * as IAuthorizable from '../generated-artifacts/IAuthorizable.json';
import * as IOwnable from '../generated-artifacts/IOwnable.json';
import * as LibAddress from '../generated-artifacts/LibAddress.json';
import * as LibAddressArray from '../generated-artifacts/LibAddressArray.json';
import * as LibAddressArrayRichErrors from '../generated-artifacts/LibAddressArrayRichErrors.json';
import * as LibAuthorizableRichErrors from '../generated-artifacts/LibAuthorizableRichErrors.json';
import * as LibBytes from '../generated-artifacts/LibBytes.json';
import * as LibBytesRichErrors from '../generated-artifacts/LibBytesRichErrors.json';
import * as LibEIP1271 from '../generated-artifacts/LibEIP1271.json';
import * as LibEIP712 from '../generated-artifacts/LibEIP712.json';
import * as LibFractions from '../generated-artifacts/LibFractions.json';
import * as LibOwnableRichErrors from '../generated-artifacts/LibOwnableRichErrors.json';
import * as LibReentrancyGuardRichErrors from '../generated-artifacts/LibReentrancyGuardRichErrors.json';
import * as LibRichErrors from '../generated-artifacts/LibRichErrors.json';
import * as LibSafeMath from '../generated-artifacts/LibSafeMath.json';
import * as LibSafeMathRichErrors from '../generated-artifacts/LibSafeMathRichErrors.json';
import * as Ownable from '../generated-artifacts/Ownable.json';
import * as ReentrancyGuard from '../generated-artifacts/ReentrancyGuard.json';
import * as Refundable from '../generated-artifacts/Refundable.json';
export const artifacts = {
    Authorizable: Authorizable as ContractArtifact,
    IAuthorizable: IAuthorizable as ContractArtifact,
    IOwnable: IOwnable as ContractArtifact,
    LibAddress: LibAddress as ContractArtifact,
    LibAddressArray: LibAddressArray as ContractArtifact,
    LibAddressArrayRichErrors: LibAddressArrayRichErrors as ContractArtifact,
    LibAuthorizableRichErrors: LibAuthorizableRichErrors as ContractArtifact,
    LibBytes: LibBytes as ContractArtifact,
    LibBytesRichErrors: LibBytesRichErrors as ContractArtifact,
    LibEIP1271: LibEIP1271 as ContractArtifact,
    LibEIP712: LibEIP712 as ContractArtifact,
    LibFractions: LibFractions as ContractArtifact,
    LibOwnableRichErrors: LibOwnableRichErrors as ContractArtifact,
    LibReentrancyGuardRichErrors: LibReentrancyGuardRichErrors as ContractArtifact,
    LibRichErrors: LibRichErrors as ContractArtifact,
    LibSafeMath: LibSafeMath as ContractArtifact,
    LibSafeMathRichErrors: LibSafeMathRichErrors as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ReentrancyGuard: ReentrancyGuard as ContractArtifact,
    Refundable: Refundable as ContractArtifact,
};
