/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as LibAddress from '../generated-artifacts/LibAddress.json';
import * as IOwnable from '../generated-artifacts/IOwnable.json';
import * as LibBytes from '../generated-artifacts/LibBytes.json';
import * as LibEIP712 from '../generated-artifacts/LibEIP712.json';
import * as Ownable from '../generated-artifacts/Ownable.json';
import * as ReentrancyGuard from '../generated-artifacts/ReentrancyGuard.json';
import * as RichErrors from '../generated-artifacts/RichErrors.json';
import * as SafeMath from '../generated-artifacts/SafeMath.json';
import * as TestConstants from '../generated-artifacts/TestConstants.json';
import * as TestLibAddressArray from '../generated-artifacts/TestLibAddressArray.json';
import * as TestLibBytes from '../generated-artifacts/TestLibBytes.json';
export const artifacts = {
    LibAddress: LibAddress as ContractArtifact,
    LibBytes: LibBytes as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ReentrancyGuard: ReentrancyGuard as ContractArtifact,
    SafeMath: SafeMath as ContractArtifact,
    LibEIP712: LibEIP712 as ContractArtifact,
    RichErrors: RichErrors as ContractArtifact,
    IOwnable: IOwnable as ContractArtifact,
    TestConstants: TestConstants as ContractArtifact,
    TestLibAddressArray: TestLibAddressArray as ContractArtifact,
    TestLibBytes: TestLibBytes as ContractArtifact,
};
