/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as MultiSigWalletWithTimeLock from '../generated-artifacts/MultiSigWalletWithTimeLock.json';
import * as ZeroExGovernor from '../generated-artifacts/ZeroExGovernor.json';
export const artifacts = {
    MultiSigWalletWithTimeLock: MultiSigWalletWithTimeLock as ContractArtifact,
    ZeroExGovernor: ZeroExGovernor as ContractArtifact,
};
