from distutils.core import Command

class clean(Command):
    def initialize_options(self: clean) -> None: ...
    def finalize_options(self: clean) -> None: ...
    def run(self: clean) -> None: ...
    ...
