/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Forwarder from '../generated-artifacts/Forwarder.json';
export const artifacts = { Forwarder: Forwarder as ContractArtifact };
