#!/usr/bin/env python

"""Script to install all packages in editable mode (pip install -e .)."""

from os import path
import subprocess

# install all packages
subprocess.check_call(
    (
        path.join(".", "cmd_pkgs_in_dep_order.py") + " pip install -e .[dev]"
    ).split()
)
