#!/usr/bin/env python

"""Install all packages in non-editable mode (no -e on pip install)."""

from os import path
import subprocess

# install all packages
subprocess.check_call(
    (
        path.join(".", "cmd_pkgs_in_dep_order.py") + " pip install .[dev]"
    ).split()
)
