/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as ERC1155Proxy from '../test/generated-artifacts/ERC1155Proxy.json';
import * as ERC20BridgeProxy from '../test/generated-artifacts/ERC20BridgeProxy.json';
import * as ERC20Proxy from '../test/generated-artifacts/ERC20Proxy.json';
import * as ERC721Proxy from '../test/generated-artifacts/ERC721Proxy.json';
import * as Eth2DaiBridge from '../test/generated-artifacts/Eth2DaiBridge.json';
import * as IAssetData from '../test/generated-artifacts/IAssetData.json';
import * as IAssetProxy from '../test/generated-artifacts/IAssetProxy.json';
import * as IAssetProxyDispatcher from '../test/generated-artifacts/IAssetProxyDispatcher.json';
import * as IAuthorizable from '../test/generated-artifacts/IAuthorizable.json';
import * as IERC20Bridge from '../test/generated-artifacts/IERC20Bridge.json';
import * as IEth2Dai from '../test/generated-artifacts/IEth2Dai.json';
import * as IKyberNetworkProxy from '../test/generated-artifacts/IKyberNetworkProxy.json';
import * as IUniswapExchange from '../test/generated-artifacts/IUniswapExchange.json';
import * as IUniswapExchangeFactory from '../test/generated-artifacts/IUniswapExchangeFactory.json';
import * as KyberBridge from '../test/generated-artifacts/KyberBridge.json';
import * as MixinAssetProxyDispatcher from '../test/generated-artifacts/MixinAssetProxyDispatcher.json';
import * as MixinAuthorizable from '../test/generated-artifacts/MixinAuthorizable.json';
import * as MultiAssetProxy from '../test/generated-artifacts/MultiAssetProxy.json';
import * as Ownable from '../test/generated-artifacts/Ownable.json';
import * as StaticCallProxy from '../test/generated-artifacts/StaticCallProxy.json';
import * as TestERC20Bridge from '../test/generated-artifacts/TestERC20Bridge.json';
import * as TestEth2DaiBridge from '../test/generated-artifacts/TestEth2DaiBridge.json';
import * as TestKyberBridge from '../test/generated-artifacts/TestKyberBridge.json';
import * as TestStaticCallTarget from '../test/generated-artifacts/TestStaticCallTarget.json';
import * as TestUniswapBridge from '../test/generated-artifacts/TestUniswapBridge.json';
import * as UniswapBridge from '../test/generated-artifacts/UniswapBridge.json';
export const artifacts = {
    MixinAssetProxyDispatcher: MixinAssetProxyDispatcher as ContractArtifact,
    MixinAuthorizable: MixinAuthorizable as ContractArtifact,
    Ownable: Ownable as ContractArtifact,
    ERC1155Proxy: ERC1155Proxy as ContractArtifact,
    ERC20BridgeProxy: ERC20BridgeProxy as ContractArtifact,
    ERC20Proxy: ERC20Proxy as ContractArtifact,
    ERC721Proxy: ERC721Proxy as ContractArtifact,
    MultiAssetProxy: MultiAssetProxy as ContractArtifact,
    StaticCallProxy: StaticCallProxy as ContractArtifact,
    Eth2DaiBridge: Eth2DaiBridge as ContractArtifact,
    KyberBridge: KyberBridge as ContractArtifact,
    UniswapBridge: UniswapBridge as ContractArtifact,
    IAssetData: IAssetData as ContractArtifact,
    IAssetProxy: IAssetProxy as ContractArtifact,
    IAssetProxyDispatcher: IAssetProxyDispatcher as ContractArtifact,
    IAuthorizable: IAuthorizable as ContractArtifact,
    IERC20Bridge: IERC20Bridge as ContractArtifact,
    IEth2Dai: IEth2Dai as ContractArtifact,
    IKyberNetworkProxy: IKyberNetworkProxy as ContractArtifact,
    IUniswapExchange: IUniswapExchange as ContractArtifact,
    IUniswapExchangeFactory: IUniswapExchangeFactory as ContractArtifact,
    TestERC20Bridge: TestERC20Bridge as ContractArtifact,
    TestEth2DaiBridge: TestEth2DaiBridge as ContractArtifact,
    TestKyberBridge: TestKyberBridge as ContractArtifact,
    TestStaticCallTarget: TestStaticCallTarget as ContractArtifact,
    TestUniswapBridge: TestUniswapBridge as ContractArtifact,
};
