/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as RichRevertsDecoder from '../generated-artifacts/RichRevertsDecoder.json';
export const artifacts = { RichRevertsDecoder: RichRevertsDecoder as ContractArtifact };
