/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as FillQuoteTransformer from '../generated-artifacts/FillQuoteTransformer.json';
import * as FullMigration from '../generated-artifacts/FullMigration.json';
import * as IAllowanceTarget from '../generated-artifacts/IAllowanceTarget.json';
import * as IERC20Transformer from '../generated-artifacts/IERC20Transformer.json';
import * as IFlashWallet from '../generated-artifacts/IFlashWallet.json';
import * as InitialMigration from '../generated-artifacts/InitialMigration.json';
import * as IOwnable from '../generated-artifacts/IOwnable.json';
import * as ISimpleFunctionRegistry from '../generated-artifacts/ISimpleFunctionRegistry.json';
import * as ITokenSpender from '../generated-artifacts/ITokenSpender.json';
import * as ITransformERC20 from '../generated-artifacts/ITransformERC20.json';
import * as PayTakerTransformer from '../generated-artifacts/PayTakerTransformer.json';
import * as WethTransformer from '../generated-artifacts/WethTransformer.json';
import * as ZeroEx from '../generated-artifacts/ZeroEx.json';
export const artifacts = {
    ZeroEx: ZeroEx as ContractArtifact,
    FullMigration: FullMigration as ContractArtifact,
    InitialMigration: InitialMigration as ContractArtifact,
    IFlashWallet: IFlashWallet as ContractArtifact,
    IAllowanceTarget: IAllowanceTarget as ContractArtifact,
    IERC20Transformer: IERC20Transformer as ContractArtifact,
    IOwnable: IOwnable as ContractArtifact,
    ISimpleFunctionRegistry: ISimpleFunctionRegistry as ContractArtifact,
    ITokenSpender: ITokenSpender as ContractArtifact,
    ITransformERC20: ITransformERC20 as ContractArtifact,
    FillQuoteTransformer: FillQuoteTransformer as ContractArtifact,
    PayTakerTransformer: PayTakerTransformer as ContractArtifact,
    WethTransformer: WethTransformer as ContractArtifact,
};
