"use strict";
function __export(m) {
    for (var p in m) if (!exports.hasOwnProperty(p)) exports[p] = m[p];
}
Object.defineProperty(exports, "__esModule", { value: true });
/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
__export(require("../test/generated-wrappers/dummy_liquidity_provider"));
__export(require("../test/generated-wrappers/dummy_liquidity_provider_registry"));
__export(require("../test/generated-wrappers/erc20_bridge_sampler"));
__export(require("../test/generated-wrappers/i_curve"));
__export(require("../test/generated-wrappers/i_dev_utils"));
__export(require("../test/generated-wrappers/i_erc20_bridge_sampler"));
__export(require("../test/generated-wrappers/i_eth2_dai"));
__export(require("../test/generated-wrappers/i_kyber_network"));
__export(require("../test/generated-wrappers/i_liquidity_provider"));
__export(require("../test/generated-wrappers/i_liquidity_provider_registry"));
__export(require("../test/generated-wrappers/i_uniswap_exchange_quotes"));
__export(require("../test/generated-wrappers/test_erc20_bridge_sampler"));
//# sourceMappingURL=wrappers.js.map