/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as DummyERC721Receiver from '../generated-artifacts/DummyERC721Receiver.json';
import * as DummyERC721Token from '../generated-artifacts/DummyERC721Token.json';
import * as ERC721Token from '../generated-artifacts/ERC721Token.json';
import * as IERC721Receiver from '../generated-artifacts/IERC721Receiver.json';
export const artifacts = {
    DummyERC721Token: DummyERC721Token as ContractArtifact,
    ERC721Token: ERC721Token as ContractArtifact,
    IERC721Receiver: IERC721Receiver as ContractArtifact,
    DummyERC721Receiver: DummyERC721Receiver as ContractArtifact,
};
