/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as DevUtils from '../generated-artifacts/DevUtils.json';
export const artifacts = { DevUtils: DevUtils as ContractArtifact };
