export const orderSchema = {
    id: '/Order',
    properties: {
        maker: { $ref: '/OrderTaker' },
        taker: { $ref: '/OrderTaker' },
        makerFee: { type: 'string' },
        takerFee: { type: 'string' },
        salt: { type: 'string' },
        ecSignature: { $ref: '/SignatureData' },
        expirationUnixTimestampSec: { type: 'string' },
        feeRecipient: { type: 'string' },
        exchangeContractAddress: { type: 'string' },
        networkId: { type: 'number' },
    },
    required: [
        'maker',
        'taker',
        'makerFee',
        'takerFee',
        'salt',
        'ecSignature',
        'expirationUnixTimestampSec',
        'feeRecipient',
        'exchangeContractAddress',
        'networkId',
    ],
    type: 'object',
};
