export const signedOrderSchema = {
    id: '/SignedOrder',
    properties: {
        maker: { type: 'string' },
        taker: { type: 'string' },
        makerTokenAddress: { type: 'string' },
        takerTokenAddress: { type: 'string' },
        makerFee: { type: 'string' },
        takerFee: { type: 'string' },
        makerTokenAmount: { type: 'string' },
        takerTokenAmount: { type: 'string' },
        salt: { type: 'string' },
        ecSignature: { $ref: '/SignatureData' },
        expirationUnixTimestampSec: { type: 'string' },
        feeRecipient: { type: 'string' },
        exchangeContractAddress: { type: 'string' },
    },
    required: [
        'maker',
        'taker',
        'makerTokenAddress',
        'takerTokenAddress',
        'makerFee',
        'takerFee',
        'makerTokenAmount',
        'takerTokenAmount',
        'salt',
        'ecSignature',
        'expirationUnixTimestampSec',
        'feeRecipient',
        'exchangeContractAddress',
    ],
    type: 'object',
};
