/*
 * -----------------------------------------------------------------------------
 * Warning: This file is auto-generated by contracts-gen. Don't edit manually.
 * -----------------------------------------------------------------------------
 */
import { ContractArtifact } from 'ethereum-types';

import * as Coordinator from '../test/generated-artifacts/Coordinator.json';
import * as CoordinatorRegistry from '../test/generated-artifacts/CoordinatorRegistry.json';
import * as ICoordinatorApprovalVerifier from '../test/generated-artifacts/ICoordinatorApprovalVerifier.json';
import * as ICoordinatorCore from '../test/generated-artifacts/ICoordinatorCore.json';
import * as ICoordinatorRegistryCore from '../test/generated-artifacts/ICoordinatorRegistryCore.json';
import * as ICoordinatorSignatureValidator from '../test/generated-artifacts/ICoordinatorSignatureValidator.json';
import * as LibConstants from '../test/generated-artifacts/LibConstants.json';
import * as LibCoordinatorApproval from '../test/generated-artifacts/LibCoordinatorApproval.json';
import * as LibCoordinatorRichErrors from '../test/generated-artifacts/LibCoordinatorRichErrors.json';
import * as LibEIP712CoordinatorDomain from '../test/generated-artifacts/LibEIP712CoordinatorDomain.json';
import * as MixinCoordinatorApprovalVerifier from '../test/generated-artifacts/MixinCoordinatorApprovalVerifier.json';
import * as MixinCoordinatorCore from '../test/generated-artifacts/MixinCoordinatorCore.json';
import * as MixinCoordinatorRegistryCore from '../test/generated-artifacts/MixinCoordinatorRegistryCore.json';
import * as MixinSignatureValidator from '../test/generated-artifacts/MixinSignatureValidator.json';
export const artifacts = {
    Coordinator: Coordinator as ContractArtifact,
    MixinCoordinatorApprovalVerifier: MixinCoordinatorApprovalVerifier as ContractArtifact,
    MixinCoordinatorCore: MixinCoordinatorCore as ContractArtifact,
    MixinSignatureValidator: MixinSignatureValidator as ContractArtifact,
    ICoordinatorApprovalVerifier: ICoordinatorApprovalVerifier as ContractArtifact,
    ICoordinatorCore: ICoordinatorCore as ContractArtifact,
    ICoordinatorSignatureValidator: ICoordinatorSignatureValidator as ContractArtifact,
    LibConstants: LibConstants as ContractArtifact,
    LibCoordinatorApproval: LibCoordinatorApproval as ContractArtifact,
    LibCoordinatorRichErrors: LibCoordinatorRichErrors as ContractArtifact,
    LibEIP712CoordinatorDomain: LibEIP712CoordinatorDomain as ContractArtifact,
    CoordinatorRegistry: CoordinatorRegistry as ContractArtifact,
    MixinCoordinatorRegistryCore: MixinCoordinatorRegistryCore as ContractArtifact,
    ICoordinatorRegistryCore: ICoordinatorRegistryCore as ContractArtifact,
};
